name = "ballot-app-server"
main = "server/dist/index.js"
compatibility_date = "2024-12-01"

# Environment variables for Honeycomb integration
# Set these in the Cloudflare dashboard or via wrangler secret
[vars]
HONEYCOMB_DATASET = "ballot-app"
NODE_ENV = "production"

[[env.development]]
name = "ballot-app-server-dev"
[env.development.vars]
HONEYCOMB_DATASET = "ballot-app-dev"
NODE_ENV = "development"

[[env.production]]
name = "ballot-app-server"
[env.production.vars]
HONEYCOMB_DATASET = "ballot-app"
NODE_ENV = "production"